### ISSUE TITLE
Warn about trove classifiers when releasing?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.releaser#8]
We could create another zest.releaser plugin that checks before doing a release if the version about to be released has all the trove classifiers according to the branch that the release is about to be made compared to what sources.cfg on buildout.coredev state.

This can be easily known with http://jenkins.plone.org/roboto/sources.json

I'm wondering though if this is something to be done at release time or instead a jenkins job/mr.roboto view could do the reporting and every now and then we check for it?

**Comment by gforcada** [comment]
@plone/release-team any input on this?

**Comment by mauritsvanrees** [comment]
Huh, I see I wasn't watching this repo... Doing so starting now.

I usually check it manually, I have a script that does various things, including grepping for Plone and Python classifiers and grepping for the package in versions/checkouts in clones of the three coredev branches.  Most of the package are okay now, though there are always shifts.

Tricky: the Plone 5.1 classifier does not exist yet. I asked several months ago, but they did not want to add it at the time, because Plone 5.1 was not near release yet. So we need to keep 5.0 as classifier for packages targeting 5.1.

Trickier: I think there are several packages for which the master branch is used on 5.0 coredev only, but the newer version would work on 4.3 as well.  For example: plone.namedfile had csrf fixes so 3.0.0 was created and was used on Plone 5, where 4.3 used 2.x. Then in Plone 4.3.8 we decided we wanted the csrf fixes in 4.3 as well, so we started using 3.x, with minor changes for better compatibility.   But `setup.py` is only listing the 5.0 classifier. Well, I fixed that just now.
But I'm pretty sure there are a few other packages that are a better example. Maybe diazo. Plone 4.3 uses branch 1.1.x. But master lists Python classifiers for 2.6, 2.7, 3, 3.3, 3.4. There is no Plone classifier so we might want to skip testing this package. But from the Plone perspective only Python 2.7 would be needed, so plugin would probably warn about that, which is not good.

So we might get some wrong warnings. We might check a `.travis.yml` to see if other Python/Plone versions should be kept, but that could be tricky to parse reliably.

Anyway, generally this is a good idea.

I would be happy with this at release time. +1 for that. It also serves as a warning: "This package is used by three coredev branches, so you should update versions/checkouts in all three after you are done." 

Some roboto Jenkins job could work too: if someone wants to do a few usually easy fixes in packages, he can go to the report page and look for work.

**Comment by gforcada** [comment]
In `plone/meta` we are starting to use [`check-python-versions`](https://pypi.org/project/check-python-versions) 🎉
